dist: trusty
sudo: required
language: c
addons:
  apt:
    update: true
before_script:
- sudo apt install sdcc
script:
- make -C firmware CFLAGS=--Werror SDAR="sdcclib r"
- make -C examples CFLAGS=--Werror SDAR="sdcclib r"
